-- MySQL Script generated by MySQL Workbench
-- ter 05 nov 2019 20:13:23 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE DATABASE ROSEBD;

USE `ROSEBD` ;

-- -----------------------------------------------------
-- Table `ROSEBD`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ROSEBD`.`Usuario` (
  `cnpj` INT(11) NOT NULL,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `telefone` VARCHAR(45) NULL DEFAULT NULL,
  `caminho_logomarca` VARCHAR(200) NULL DEFAULT NULL,
  `email` VARCHAR(200) NOT NULL,
  `senha` VARCHAR(45) NULL,
  PRIMARY KEY (`cnpj`, `email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ROSEBD`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ROSEBD`.`Compra` (
  `idCompra` INT(11) NOT NULL AUTO_INCREMENT,
  `Usuario_cnpj` INT(11) NOT NULL,
  `data` DATE NULL DEFAULT NULL,
  `valor_total` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`idCompra`, `Usuario_cnpj`),
  INDEX `fk_Compra_Usuario1_idx` (`Usuario_cnpj` ASC),
  CONSTRAINT `fk_Compra_Usuario1`
    FOREIGN KEY (`Usuario_cnpj`)
    REFERENCES `ROSEBD`.`Usuario` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ROSEBD`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ROSEBD`.`Fornecedor` (
  `idFornecedor` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `endereco` VARCHAR(45) NULL DEFAULT NULL,
  `Usuario_cnpj` INT(11) NOT NULL,
  PRIMARY KEY (`idFornecedor`, `Usuario_cnpj`),
  INDEX `fk_Fornecedor_Usuario1_idx` (`Usuario_cnpj` ASC),
  CONSTRAINT `fk_Fornecedor_Usuario1`
    FOREIGN KEY (`Usuario_cnpj`)
    REFERENCES `ROSEBD`.`Usuario` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ROSEBD`.`Material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ROSEBD`.`Material` (
  `idMaterial` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `marca` VARCHAR(45) NULL DEFAULT NULL,
  `Usuario_cnpj` INT(11) NOT NULL,
  PRIMARY KEY (`idMaterial`, `Usuario_cnpj`),
  INDEX `fk_Material_Usuario1_idx` (`Usuario_cnpj` ASC),
  CONSTRAINT `fk_Material_Usuario1`
    FOREIGN KEY (`Usuario_cnpj`)
    REFERENCES `ROSEBD`.`Usuario` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ROSEBD`.`Material_Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ROSEBD`.`Material_Fornecedor` (
  `Material_idMaterial` INT(11) NOT NULL AUTO_INCREMENT,
  `Fornecedor_idFornecedor` INT(11) NOT NULL,
  `preco` FLOAT NULL DEFAULT NULL,
  `Fornecedor_idFornecedor1` INT(11) NOT NULL,
  `Fornecedor_Usuario_cnpj` INT(11) NOT NULL,
  PRIMARY KEY (`Material_idMaterial`, `Fornecedor_idFornecedor`, `Fornecedor_idFornecedor1`, `Fornecedor_Usuario_cnpj`),
  INDEX `fk_Material_has_Fornecedor_Material1_idx` (`Material_idMaterial` ASC),
  INDEX `fk_Material_Fornecedor_Fornecedor1_idx` (`Fornecedor_idFornecedor1` ASC, `Fornecedor_Usuario_cnpj` ASC),
  CONSTRAINT `fk_Material_Fornecedor_Fornecedor1`
    FOREIGN KEY (`Fornecedor_idFornecedor1` , `Fornecedor_Usuario_cnpj`)
    REFERENCES `ROSEBD`.`Fornecedor` (`idFornecedor` , `Usuario_cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Material_has_Fornecedor_Material1`
    FOREIGN KEY (`Material_idMaterial`)
    REFERENCES `ROSEBD`.`Material` (`idMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ROSEBD`.`Compra_Material_Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ROSEBD`.`Compra_Material_Fornecedor` (
  `Material_Fornecedor_Material_idMaterial` INT(11) NOT NULL AUTO_INCREMENT,
  `Material_Fornecedor_Fornecedor_idFornecedor` INT(11) NOT NULL,
  `quantidade` INT(11) NULL DEFAULT NULL,
  `Compra_idCompra` INT(11) NOT NULL,
  `Compra_Usuario_cnpj` INT(11) NOT NULL,
  PRIMARY KEY (`Material_Fornecedor_Material_idMaterial`, `Material_Fornecedor_Fornecedor_idFornecedor`, `Compra_idCompra`, `Compra_Usuario_cnpj`),
  INDEX `fk_Compra_Material_Fornecedor_Material_Fornecedor1_idx` (`Material_Fornecedor_Material_idMaterial` ASC, `Material_Fornecedor_Fornecedor_idFornecedor` ASC),
  INDEX `fk_Compra_Material_Fornecedor_Compra1_idx` (`Compra_idCompra` ASC, `Compra_Usuario_cnpj` ASC),
  CONSTRAINT `fk_Compra_Material_Fornecedor_Compra1`
    FOREIGN KEY (`Compra_idCompra` , `Compra_Usuario_cnpj`)
    REFERENCES `ROSEBD`.`Compra` (`idCompra` , `Usuario_cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compra_Material_Fornecedor_Material_Fornecedor1`
    FOREIGN KEY (`Material_Fornecedor_Material_idMaterial` , `Material_Fornecedor_Fornecedor_idFornecedor`)
    REFERENCES `ROSEBD`.`Material_Fornecedor` (`Material_idMaterial` , `Fornecedor_idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ROSEBD`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ROSEBD`.`Estoque` (
  `idEstoque` INT(11) NOT NULL AUTO_INCREMENT,
  `Usuario_cnpj` INT(11) NOT NULL,
  PRIMARY KEY (`idEstoque`, `Usuario_cnpj`),
  INDEX `fk_Estoque_Usuario1_idx` (`Usuario_cnpj` ASC),
  CONSTRAINT `fk_Estoque_Usuario1`
    FOREIGN KEY (`Usuario_cnpj`)
    REFERENCES `ROSEBD`.`Usuario` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ROSEBD`.`Estoque_Material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ROSEBD`.`Estoque_Material` (
  `Material_idMaterial` INT(11) NOT NULL AUTO_INCREMENT,
  `quantidade` INT(11) NULL DEFAULT NULL,
  `Estoque_idEstoque` INT(11) NOT NULL,
  `Estoque_Usuario_cnpj` INT(11) NOT NULL,
  PRIMARY KEY (`Material_idMaterial`, `Estoque_idEstoque`, `Estoque_Usuario_cnpj`),
  INDEX `fk_Estoque_Material_Material1_idx` (`Material_idMaterial` ASC),
  INDEX `fk_Estoque_Material_Estoque1_idx` (`Estoque_idEstoque` ASC, `Estoque_Usuario_cnpj` ASC),
  CONSTRAINT `fk_Estoque_Material_Estoque1`
    FOREIGN KEY (`Estoque_idEstoque` , `Estoque_Usuario_cnpj`)
    REFERENCES `ROSEBD`.`Estoque` (`idEstoque` , `Usuario_cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estoque_Material_Material1`
    FOREIGN KEY (`Material_idMaterial`)
    REFERENCES `ROSEBD`.`Material` (`idMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ROSEBD`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ROSEBD`.`Funcionario` (
  `idFuncionario` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `valorDiaria` VARCHAR(45) NULL DEFAULT NULL,
  `qntDias` INT(11) NULL DEFAULT NULL,
  `vale_concedido` FLOAT NULL DEFAULT NULL,
  `salario_mensal` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`idFuncionario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ROSEBD`.`Lucro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ROSEBD`.`Lucro` (
  `idLucro` INT(11) NOT NULL AUTO_INCREMENT,
  `data` DATE NULL DEFAULT NULL,
  `Usuario_cnpj` INT(11) NOT NULL,
  PRIMARY KEY (`idLucro`, `Usuario_cnpj`),
  INDEX `fk_Lucro_Usuario1_idx` (`Usuario_cnpj` ASC),
  CONSTRAINT `fk_Lucro_Usuario1`
    FOREIGN KEY (`Usuario_cnpj`)
    REFERENCES `ROSEBD`.`Usuario` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ROSEBD`.`Funcionario_Lucro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ROSEBD`.`Funcionario_Lucro` (
  `Funcionario_idFuncionario` INT(11) NOT NULL AUTO_INCREMENT,
  `Lucro_idLucro` INT(11) NOT NULL,
  `Lucro_Usuario_cnpj` INT(11) NOT NULL,
  PRIMARY KEY (`Funcionario_idFuncionario`, `Lucro_idLucro`, `Lucro_Usuario_cnpj`),
  INDEX `fk_Funcionario_has_Lucro_Lucro1_idx` (`Lucro_idLucro` ASC, `Lucro_Usuario_cnpj` ASC),
  INDEX `fk_Funcionario_has_Lucro_Funcionario1_idx` (`Funcionario_idFuncionario` ASC),
  CONSTRAINT `fk_Funcionario_has_Lucro_Funcionario1`
    FOREIGN KEY (`Funcionario_idFuncionario`)
    REFERENCES `ROSEBD`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_has_Lucro_Lucro1`
    FOREIGN KEY (`Lucro_idLucro` , `Lucro_Usuario_cnpj`)
    REFERENCES `ROSEBD`.`Lucro` (`idLucro` , `Usuario_cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ROSEBD`.`Tamanho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ROSEBD`.`Tamanho` (
  `idTamanho` INT(11) NOT NULL,
  `tamanho` VARCHAR(5) NULL DEFAULT NULL,
  `Usuario_cnpj` INT(11) NOT NULL,
  PRIMARY KEY (`idTamanho`, `Usuario_cnpj`),
  INDEX `fk_Tamanho_Usuario1_idx` (`Usuario_cnpj` ASC),
  CONSTRAINT `fk_Tamanho_Usuario1`
    FOREIGN KEY (`Usuario_cnpj`)
    REFERENCES `ROSEBD`.`Usuario` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ROSEBD`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ROSEBD`.`Produto` (
  `idProduto` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `Usuario_cnpj` INT(11) NOT NULL,
  `categoria` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idProduto`, `Usuario_cnpj`),
  INDEX `fk_Modelo_Usuario1_idx` (`Usuario_cnpj` ASC),
  CONSTRAINT `fk_Modelo_Usuario1`
    FOREIGN KEY (`Usuario_cnpj`)
    REFERENCES `ROSEBD`.`Usuario` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ROSEBD`.`Modelo_Tamanho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ROSEBD`.`Modelo_Tamanho` (
  `Produto_idProduto` INT(11) NOT NULL,
  `Produto_Usuario_cnpj` INT(11) NOT NULL,
  `preco` FLOAT NULL DEFAULT NULL,
  `Tamanho_idTamanho` INT(11) NOT NULL,
  `Tamanho_Usuario_cnpj` INT(11) NOT NULL,
  PRIMARY KEY (`Produto_idProduto`, `Produto_Usuario_cnpj`, `Tamanho_idTamanho`, `Tamanho_Usuario_cnpj`),
  INDEX `fk_Tamanho_has_Produto_Produto1_idx` (`Produto_idProduto` ASC, `Produto_Usuario_cnpj` ASC),
  INDEX `fk_Modelo_Tamanho_Tamanho1_idx` (`Tamanho_idTamanho` ASC, `Tamanho_Usuario_cnpj` ASC),
  CONSTRAINT `fk_Modelo_Tamanho_Tamanho1`
    FOREIGN KEY (`Tamanho_idTamanho` , `Tamanho_Usuario_cnpj`)
    REFERENCES `ROSEBD`.`Tamanho` (`idTamanho` , `Usuario_cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tamanho_has_Produto_Produto1`
    FOREIGN KEY (`Produto_idProduto` , `Produto_Usuario_cnpj`)
    REFERENCES `ROSEBD`.`Produto` (`idProduto` , `Usuario_cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ROSEBD`.`Producao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ROSEBD`.`Producao` (
  `idProducao` INT(11) NOT NULL AUTO_INCREMENT,
  `data` DATE NULL DEFAULT NULL,
  `Usuario_cnpj` INT(11) NOT NULL,
  PRIMARY KEY (`idProducao`, `Usuario_cnpj`),
  INDEX `fk_Producao_Usuario1_idx` (`Usuario_cnpj` ASC),
  CONSTRAINT `fk_Producao_Usuario1`
    FOREIGN KEY (`Usuario_cnpj`)
    REFERENCES `ROSEBD`.`Usuario` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ROSEBD`.`Producao_Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ROSEBD`.`Producao_Produto` (
  `Producao_idProducao` INT(11) NOT NULL AUTO_INCREMENT,
  `quantidade` INT(11) NULL DEFAULT NULL,
  `Produto_idProduto` INT(11) NOT NULL,
  `Producao_idProducao1` INT(11) NOT NULL,
  `Producao_Usuario_cnpj` INT(11) NOT NULL,
  `Produto_idProduto1` INT(11) NOT NULL,
  `Produto_Usuario_cnpj` INT(11) NOT NULL,
  PRIMARY KEY (`Producao_idProducao`, `Produto_idProduto`, `Producao_idProducao1`, `Producao_Usuario_cnpj`, `Produto_idProduto1`, `Produto_Usuario_cnpj`),
  INDEX `fk_Producao_Produto_Producao1_idx` (`Producao_idProducao1` ASC, `Producao_Usuario_cnpj` ASC),
  INDEX `fk_Producao_Produto_Produto1_idx` (`Produto_idProduto1` ASC, `Produto_Usuario_cnpj` ASC),
  CONSTRAINT `fk_Producao_Modelo_Modelo1`
    FOREIGN KEY (`Produto_idProduto1` , `Produto_Usuario_cnpj`)
    REFERENCES `ROSEBD`.`Produto` (`idProduto` , `Usuario_cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producao_Modelo_Producao1`
    FOREIGN KEY (`Producao_idProducao1` , `Producao_Usuario_cnpj`)
    REFERENCES `ROSEBD`.`Producao` (`idProducao` , `Usuario_cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ROSEBD`.`Produto_Material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ROSEBD`.`Produto_Material` (
  `Material_idMaterial` INT(11) NOT NULL AUTO_INCREMENT,
  `quantidade_gasta` INT(11) NULL DEFAULT NULL,
  `Produto_idProduto` INT(11) NOT NULL,
  `Produto_Usuario_cnpj` INT(11) NOT NULL,
  `unidade_de_medida` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`Material_idMaterial`, `Produto_idProduto`, `Produto_Usuario_cnpj`),
  INDEX `fk_Produto_has_Material_Material1_idx` (`Material_idMaterial` ASC),
  INDEX `fk_Produto_Material_Produto1_idx` (`Produto_idProduto` ASC, `Produto_Usuario_cnpj` ASC),
  CONSTRAINT `fk_Modelo_Material_Modelo1`
    FOREIGN KEY (`Produto_idProduto` , `Produto_Usuario_cnpj`)
    REFERENCES `ROSEBD`.`Produto` (`idProduto` , `Usuario_cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Modelo_has_Material_Material1`
    FOREIGN KEY (`Material_idMaterial`)
    REFERENCES `ROSEBD`.`Material` (`idMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ROSEBD`.`Venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ROSEBD`.`Venda` (
  `idVenda` INT(11) NOT NULL AUTO_INCREMENT,
  `quantidade_vendida` INT(11) NULL DEFAULT NULL,
  `data` DATE NULL DEFAULT NULL,
  `destino` VARCHAR(200) NULL DEFAULT NULL,
  `Lucro_idLucro` INT(11) NOT NULL,
  `Producao_Produto_Producao_idProducao` INT(11) NOT NULL,
  `Producao_Produto_Produto_idProduto` INT(11) NOT NULL,
  `Producao_Produto_Producao_idProducao1` INT(11) NOT NULL,
  `Producao_Produto_Producao_Usuario_cnpj` INT(11) NOT NULL,
  `Producao_Produto_Produto_idProduto1` INT(11) NOT NULL,
  `Producao_Modelo_Modelo_Usuario_cnpj` INT(11) NOT NULL,
  PRIMARY KEY (`idVenda`, `Lucro_idLucro`, `Producao_Produto_Producao_idProducao`, `Producao_Produto_Produto_idProduto`, `Producao_Produto_Producao_idProducao1`, `Producao_Produto_Producao_Usuario_cnpj`, `Producao_Produto_Produto_idProduto1`, `Producao_Modelo_Modelo_Usuario_cnpj`),
  INDEX `fk_Venda_Lucro1_idx` (`Lucro_idLucro` ASC),
  INDEX `fk_Venda_Producao_Produto1_idx` (`Producao_Produto_Producao_idProducao` ASC, `Producao_Produto_Produto_idProduto` ASC, `Producao_Produto_Producao_idProducao1` ASC, `Producao_Produto_Producao_Usuario_cnpj` ASC, `Producao_Produto_Produto_idProduto1` ASC, `Producao_Modelo_Modelo_Usuario_cnpj` ASC),
  CONSTRAINT `fk_Venda_Lucro1`
    FOREIGN KEY (`Lucro_idLucro`)
    REFERENCES `ROSEBD`.`Lucro` (`idLucro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_Producao_Modelo1`
    FOREIGN KEY (`Producao_Produto_Producao_idProducao` , `Producao_Produto_Produto_idProduto` , `Producao_Produto_Producao_idProducao1` , `Producao_Produto_Producao_Usuario_cnpj` , `Producao_Produto_Produto_idProduto1` , `Producao_Modelo_Modelo_Usuario_cnpj`)
    REFERENCES `ROSEBD`.`Producao_Produto` (`Producao_idProducao` , `Produto_idProduto` , `Producao_idProducao1` , `Producao_Usuario_cnpj` , `Produto_idProduto1` , `Produto_Usuario_cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
